### ISSUE TITLE
NoReverseMatch /issue2/{slug}/ Reverse for 'profile' with keyword arguments '{'slug': ''}' not found. 1 pattern(s) tried: ['prof...

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#1842]
NoReverseMatch: Reverse for 'profile' with keyword arguments '{'slug': ''}' not found. 1 pattern(s) tried: ['profile/(?P<slug>[^/]+)/$']
(17 additional frame(s) were not displayed)
...
  File "django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)

**Comment by HanilJain** [comment]
This issue cant be replicated in local.

**Comment by HanilJain** [comment]
@DonnieBLT  it is an server error and would have been resolved by now since in previous commit qrcode library was not added to poetry and resulted in crashing of the server since you have reverted it must be have solved or you can attempt a restart.

I think this could have been a problem and if still exist I would love to work on it.

**Comment by DonnieBLT** [comment]
If you click on any issue on the site, you will get this error

**Comment by HanilJain** [comment]
I can't replicate the same error in local.
can you give me more details on it and error
