### ISSUE TITLE
make the check in a page instead of a modal see this for an example

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT#3092]
![Image](https://github.com/user-attachments/assets/01ccf3c8-5422-48a2-9765-4f165430af90)

**Comment by nitinawari** [comment]
Hi @SahilDhillon21,

I was working on Issue #3093 , as it seems closely related to the Daily Status Report modal issue. Since both issues are connected, I’ve already created a PR for the modal-related changes.

If you haven’t started working on this Issue  yet, I can go ahead and resolve it. Let me know if you’d like me to take it over or if you're already working on it.

Thanks!

**Comment by nitinawari** [comment]
No worries @SahilDhillon21! Thanks for letting me know, and feel free to finish up your changes
